AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'cac-core'
    - 'vendor'
# Style/TrailingCommaInArrayLiteral:
#   Enabled: false
# Style/TrailingCommaInHashLiteral:
#   Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Enabled: false
# Style/PercentLiteralDelimiters:
#   Enabled: false
# Style/NumericLiterals:
#   Enabled: false
# Style/FormatStringToken:
#   Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
# Gemspec/RequireMFA:
#   Enabled: false
Naming/VariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
# Style/Documentation:
#   Enabled: false
